from building import *

cwd = GetCurrentDir()
headers = [
    cwd, 
    cwd + '/../../components/drivers/include',
]

# BSP files
sources = Split("""
    startup.c
    board.c
    application.c
""")

switch = ['']
objs = DefineGroup('blackCoreStm32', src=sources, depend=switch, CPPPATH=headers)

# Common files
objs.extend(SConscript(os.path.join(cwd, '..', 'common', 'SConscript')))

Return('objs')
