import rtconfig
from building import *
Import('RTT_ROOT')


src_bsp = ['application.c', 'startup.c', 'board.c']
src_drv = ['drv_rtc.c', 'drv_usart.c', 'drv_spi.c']
src_hdl = ['hdl_interrupt.c']

# Optional bsp files
if GetDepend('BSP_USING_LED1') or GetDepend('BSP_USING_LED2'):
    src_drv.append('drv_led.c')
if GetDepend('BSP_USING_OLED'):
    src_drv.append('drv_oled.c')
if GetDepend('BSP_USING_SPISD'):
    src_drv.append('drv_sdcard.c')


headers = [ GetCurrentDir(), '../../components/drivers/include' ]
sources = src_bsp + src_drv + src_hdl
group = DefineGroup('Startup', src=sources, depend=[''], CPPPATH=headers)

Return('group')
