import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp = ['application.c', 'startup.c', 'board.c']

src_drv = ['drv_rtc.c', 'drv_usart.c', 'led.c', 'drv_spi.c', 'drv_oled.c', 'drv_sdcard.c']

src_hdl = ['hdl_interrupt.c']

src = src_bsp + src_drv + src_hdl
CPPPATH = [ GetCurrentDir() ]
CPPDEFINES = []
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
